#!/bin/sh /etc/rc.common
# Copyright (C) 2012, Jouke Witteveen

START=47
INTERFACE="lan"
CHAIN="accounting"
IPTABLES=iptables
AWK_SCRIPT='\
function goodOctets(base, mask, array,   bit, i, top) {
	array[top = 1] = and(base, mask)
	for (bit = 1; and(bit, 0xff); bit *= 2)
		if (and(mask, bit) == 0){
			for (i = 1; i <= top; ++i)
				array[top + i] = xor(array[i], bit)
			top *= 2
		}
	return top
}

BEGIN {
	FS = OFS = "."
	if(split(ARGV[1], ipaddr) != 4 || split(ARGV[2], netmask) != 4)
		exit 1
	nA = goodOctets(ipaddr[1], netmask[1], A)
	nB = goodOctets(ipaddr[2], netmask[2], B)
	nC = goodOctets(ipaddr[3], netmask[3], C)
	nD = goodOctets(ipaddr[4], netmask[4], D)
	for (a = 1; a <= nA; ++a)
		for (b = 1; b <= nB; ++b)
			for (c = 1; c <= nC; ++c)
				for (d = 1; d <= nD; ++d)
					print A[a], B[b], C[c], D[d]
}'

start() {
	$IPTABLES -N "$CHAIN" || exit 1
	config_load network
	(
		printf "*filter\n:$CHAIN -\n"
		for ipaddr in $(awk "$AWK_SCRIPT" "$(config_get "$INTERFACE" ipaddr)" "$(config_get "$INTERFACE" netmask)"); do
			printf "-A $CHAIN %s $ipaddr\n" "-s" "-d"
		done
		printf "-I FORWARD -j $CHAIN\nCOMMIT\n"
	) | ${IPTABLES}-restore --noflush
}

stop() {
	$IPTABLES -D FORWARD -j "$CHAIN"
	$IPTABLES -F "$CHAIN" && $IPTABLES -X "$CHAIN"
}

reload() {
	$IPTABLES -Z "$CHAIN" &> /dev/null
}
